---
name: Build Episodes

on:
  push:
    branches:
      - master

jobs:
  docker-image-builds:
    name: Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./episode-01/
          file: ./episode-01/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: geerlingguy/kube101:intro
